// <auto-generated />
namespace QuanLyNhaTro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class alo2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alo2));
        
        string IMigrationMetadata.Id
        {
            get { return "202206040352429_alo2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
